### ISSUE TITLE
Add a piece of documentation for `correlate`

### ISSUE THREAD

**Issue by cwayfinder** [timdeschryver/ngrx-etc#5]
Thanks for your great stuff.

Basically, I got the idea behind the `correlate` module, but it'd be great to have some explanation in the documentation or some short example.

**Comment by timdeschryver** [comment]
There were docs, but I removed them for now.
This, because the API might change and I want to test it out first.

See https://github.com/timdeschryver/ngrx-etc/blob/fd9305a126a95d9427e297721ae7a842dd738f76/README.md#correlation for the original docs. 

Feel free to use `correlate` if you'd like, I'm happy to hear some feedback about the functionality it provides.
